const {test}=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const fs=require('node:fs');const path=require('node:path');
const script=fs.readFileSync(path.join(__dirname,'../xiaoman-inquiry-center/conversions.js'),'utf8');
const api=require('../xiaoman-inquiry-center/conversions.js');const token='a'.repeat(64);
function page({url=`https://fixture.example.invalid/thank-you/?form=quick_quote&inquiry_id=FW-N7&xi_receipt=${token}`,allow=true,ledger={},kind='quick',user=true,gtag=true}={}){
 const dom=new JSDOM('<a href="https://api.whatsapp.com/send?phone=123">Contact</a>',{url,runScripts:'outside-only'}),w=dom.window,calls=[],requests=[];
 w.XIConversionConfig={site_host:'fixture.example.invalid',number_prefix:'FW-N',ga4_id:'G-FIXTURE',ads_id:'AW-123',ads_label:'FORM',whatsapp_label:'WA',email_label:'EMAIL',analytics_service:'analytics',ads_service:'ads',user_data_service:'ec',thank_you_routes:['/thank-you/','/it/thank-you/','/es/thankyou/','/fr/merci/'],endpoint:'https://fixture.example.invalid/wp-admin/admin-ajax.php?action=xi_conversion'};
 w.consentApi={consentSync(name){return {cookie:{id:name},consentGiven:true,cookieOptIn:allow&&(name!=='ec'||user)};}};
 if(gtag)w.gtag=(...args)=>calls.push(args);
 w.fetch=async(_url,opts)=>{const p=JSON.parse(opts.body);requests.push(p);if(p.op==='ack')return {json:async()=>({success:true,data:{ack:true}})};const first=!ledger[p.channel];ledger[p.channel]=true;return {json:async()=>({success:true,data:{dispatch:first,channel:p.channel,send_to:p.channel==='ga4'?'G-FIXTURE':'AW-123/FORM',inquiry_id:'FW-N7',form_type:kind,is_test:1,...(p.channel==='ads'?{user_data:{sha256_email_address:'b'.repeat(64)}}:{})}})};};
 w.eval(script);return {dom,w,calls,requests,ledger};
}
async function flush(){await new Promise(r=>setTimeout(r,10));}
test('both saved form kinds dispatch generate_lead once and use the same Ads transaction ID',async()=>{for(const kind of ['quick','detail']){const p=page({kind});await flush();const ev=p.calls.filter(c=>c[0]==='event');assert.equal(ev.length,2);assert.equal(ev.find(c=>c[1]==='generate_lead')[2].form_type,kind);assert.equal(ev.find(c=>c[1]==='conversion')[2].transaction_id,'FW-N7');for(let i=0;i<5;i++)p.w.document.dispatchEvent(new p.w.Event('rcb-consent-changed'));await flush();assert.equal(p.calls.filter(c=>c[0]==='event').length,2);p.w.close();}});
test('receipt is removed before any dispatch and customer fields are absent from GA4 params',async()=>{const p=page();assert.ok(!p.w.location.href.includes('xi_receipt'));await flush();const ga=p.calls.find(c=>c[1]==='generate_lead')[2];assert.deepEqual(Object.keys(ga).sort(),['event_callback','event_timeout','form_type','inquiry_id','send_to','test_lead']);assert.equal(p.w.localStorage.length,0);assert.equal(p.w.sessionStorage.length,0);p.w.close();});
test('server claim prevents recount in separate tabs reopening the original receipt',async()=>{const ledger={};const a=page({ledger}),b=page({ledger});await flush();assert.equal([...a.calls,...b.calls].filter(c=>c[1]==='generate_lead').length,1);assert.equal([...a.calls,...b.calls].filter(c=>c[1]==='conversion').length,1);a.w.close();b.w.close();});
test('refresh of the cleaned URL has no receipt and makes no claim',async()=>{const a=page();await flush();const b=page({url:a.w.location.href});await flush();assert.equal(b.calls.length,0);assert.equal(b.requests.length,0);a.w.close();b.w.close();});
test('translated language links lose receipt tokens, including links added after initial rendering',async()=>{const p=page();const a=p.w.document.createElement('a');a.href=`https://fixture.example.invalid/es/thankyou/?inquiry_id=FW-N7&xi_receipt=${token}`;p.w.document.body.append(a);p.w.document.dispatchEvent(new p.w.Event('DOMContentLoaded'));assert.ok(!a.href.includes('xi_receipt'));assert.ok(a.href.includes('inquiry_id=FW-N7'));a.href=`https://fixture.example.invalid/fr/merci/?xi_receipt=${token}`;a.addEventListener('click',e=>e.preventDefault());a.click();assert.ok(!a.href.includes('xi_receipt'));await flush();assert.equal(p.calls.filter(c=>c[1]==='generate_lead').length,1);p.w.close();});
test('denied or missing services never claim, including misleading cookieOptIn true without a service',async()=>{const p=page({allow:false});await flush();assert.equal(p.requests.length,0);p.w.consentApi.consentSync=()=>({cookie:null,consentGiven:true,cookieOptIn:true});p.w.document.dispatchEvent(new p.w.Event('rcb-consent-changed'));await flush();assert.equal(p.requests.length,0);p.w.close();});
test('later consent permits pending channels once, without overriding Google consent',async()=>{const p=page({allow:false});p.w.consentApi.consentSync=n=>({cookie:{id:n},consentGiven:true,cookieOptIn:true});p.w.document.dispatchEvent(new p.w.Event('rcb-consent-changed'));await flush();assert.equal(p.calls.filter(c=>c[0]==='event').length,2);assert.equal(p.calls.filter(c=>c[0]==='consent').length,0);p.w.close();});
test('enhanced data is only set around Ads and is cleared; ad_user_data denial omits it',async()=>{const a=page();await flush();const i=a.calls.findIndex(c=>c[0]==='set'&&c[2]);assert.equal(a.calls[i+1][1],'conversion');assert.deepEqual(a.calls[i+2],['set','user_data',null]);a.w.close();const b=page({user:false});await flush();assert.equal(b.calls.filter(c=>c[0]==='set'&&c[2]).length,0);b.w.close();});
test('no receipt, forged number, wrong form flag or wrong path cannot dispatch',async()=>{for(const q of ['/thank-you/','/thank-you/?form=quick_quote&inquiry_id=FW-N7','/thank-you/?form=quick_quote&inquiry_id=AX-N7&xi_receipt='+token,'/thank-you/?form=detail&inquiry_id=FW-N7&xi_receipt='+token,'/products/?form=quick_quote&inquiry_id=FW-N7&xi_receipt='+token]){const p=page({url:'https://fixture.example.invalid'+q});await flush();assert.equal(p.requests.length,0);p.w.close();}});
test('translated thank-you routes preserve the form convention',async()=>{const p=page({url:`https://fixture.example.invalid/it/thank-you/?form=quick_quote&inquiry_id=FW-N7&xi_receipt=${token}`});await flush();assert.equal(p.calls.filter(c=>c[0]==='event').length,2);p.w.close();});
test('configured Spanish and custom translated slugs dispatch; unconfigured slugs do not',async()=>{for(const route of ['/es/thankyou/','/es/thankyou','/fr/merci/','/es/thank-you/','/fr/thank-you/']){const p=page({url:`https://fixture.example.invalid${route}?form=quick_quote&inquiry_id=FW-N7&xi_receipt=${token}`});await flush();assert.equal(p.calls.filter(c=>c[0]==='event').length,route==='/es/thank-you/'||route==='/fr/thank-you/'?0:2);p.w.close();}});
test('without Google base tag readiness, receipt is not consumed',async()=>{const p=page({gtag:false});await flush();assert.equal(p.requests.length,0);p.w.gtag=(...a)=>p.calls.push(a);p.w.document.dispatchEvent(new p.w.Event('rcb-consent-changed'));await flush();assert.equal(p.calls.filter(c=>c[0]==='event').length,2);p.w.close();});
test('contact rules handle both WhatsApp hosts and email without accepting lookalike domains',()=>{assert.equal(api.contact('https://wa.me/861234567890'),'whatsapp_click');assert.equal(api.contact('https://api.whatsapp.com/send/?phone=123'),'whatsapp_click');assert.equal(api.contact('mailto:office@example.invalid'),'email_click');assert.equal(api.contact('https://wa.me.example.invalid/123'),'');assert.equal(api.contact('javascript:alert(1)'),'');});
test('contact events remain separate from saved-lead events',async()=>{const p=page({url:'https://fixture.example.invalid/contact/'});p.w.document.querySelector('a').addEventListener('click',e=>e.preventDefault());p.w.document.querySelector('a').click();await flush();assert.equal(p.calls[0][1],'whatsapp_click');assert.equal(p.calls[1][1],'conversion');assert.equal(p.calls[1][2].send_to,'AW-123/WA');assert.equal(p.calls.some(c=>c[1]==='generate_lead'),false);p.w.close();});
